* Tasks
** TODO trouver un plan adapté
** TODO ecrire une introduction







* Introduction

Ioat is a processing chain developed by the [[http://www.cesbio.ups-tlse.fr][CESBIO]] : [Centre d'Etude Spatiales de la BIOshphère] which produce a land cover image
like this one.

dire que iota utilise OTB qui utlise ITK.

Lorsque tout les paquets sont correctement installé :
Pour produire des images de classifications, vous aurez besoins de plusieurs type de données:
- des images satellites d'un capteur, ou de capteurs différents.
- des données de références si il s'agit d'une classifcation supervisée
- ...
Toutes les données en entrée de la chaine sont résumé dans la section suivante "What you need"
avant de lancer la chaine et de produire une carte de classification, il est nécessaire de renseigner à la chaine, dans un 
fichier de configuration, comment et où sont stocké les données. Cette description doit être faite dans un fichier de configuration
qui sera renseigné à la chaine. C'est également dans ce fichier que l'on renseignera divers paramètres liées au diverse méthode
de production des carte d'occupation des sols. Tout ces paramètre seront détaillés dans la section "How to configure Iota".
Le fichier de configuration correctement rempli, nous verrons comment lancer l'application.

* What you need
blablabla
un fichier de configuration pour lancer iota
* How to configure Iota

une fois le fichier de configuration paramétré, la chaine peu être lancée.
* How to launch Iota
