#!/bin/bash                                                                                                                                
#PBS -N Directory
#PBS -l select=1:ncpus=1:mem=1mb                                         
#PBS -l walltime=00:10:00
#PBS -o /ptmp/vincenta/tmp/Log/directories_out.log
#PBS -e /ptmp/vincenta/tmp/Log/directories_err.log


module load python/2.7.5
module remove xerces/2.7
module load xerces/2.8

cd $PYPATH

python oso_directory.py -root $TESTPATH









